#!/bin/bash
echo "---updating and installing python library httplib2."
sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get autoclean
sudo apt-get install x11vnc -y chromium python-pip libcurl4-openssl-dev python-dev
sudo pip install httplib2 PyVimeo nose numpy scipy pybrain pycurl glob

echo "Downloading youtube api"
cd ~/VidUploadServer/youtube
./genseed

echo "Downloading vimeo api"
cd ~/VidUploadServer/vimeo
git clone https://github.com/vimeo/vimeo.php.git

echo "Downloading dailymotion api"
cd ~/VidUploadServer/dailymotion
git clone https://github.com/dailymotion/dailymotion-sdk-python.git
cp DMup.py dailymotion-sdk-python
cd dailymotion-sdk-python
sudo python setup.py install

echo "Setting up cronjobs to run the main loop."
crontab -l >> mycron
echo "*/1 * * * * flock -n /var/run/runlock -c ~/VidUploadServer/VidUp.sh || flock -u /var/run/runlock" >> mycron
crontab mycron
rm mycron
sudo crontab -l >> mysudocron
sudo echo "@reboot flock -n /var/run/runlock -c ~/VidUploadServer/VidUp.sh || flock -u /var/run/runlock" >> mysudocron
sudo crontab mysudocron
sudo rm mysudocron
echo "Finished with install. Please run NewChannel to setup your channels."
